"use client";

import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { JURISDICTIONS, calculateGlobalTax } from "@/lib/global-tax";
import { downloadCSV } from "@/lib/documents";
import { Globe, Download, Printer, CheckCircle2, Info, Shield } from "lucide-react";

export function GlobalTaxModule({ className }: { className?: string }) {
  const [income, setIncome] = useState(85000);
  const [jurisdictionCode, setJurisdictionCode] = useState("US-CA");

  const result = calculateGlobalTax(income, jurisdictionCode);
  const j = result?.jurisdiction;

  function handleExportCSV() {
    if (!result || !j) return;
    downloadCSV(`tax-report-${j.code}-${new Date().toISOString().slice(0, 10)}.csv`,
      ["Item", "Amount", "Currency"],
      [
        ["Gross Income", result.grossIncome.toFixed(2), j.currency],
        ["Total Deductions", result.totalDeductions.toFixed(2), j.currency],
        ["Taxable Income", result.taxableIncome.toFixed(2), j.currency],
        ["Income Tax", result.incomeTax.toFixed(2), j.currency],
        [j.socialLabel, result.socialTax.toFixed(2), j.currency],
        ["Total Tax", result.totalTax.toFixed(2), j.currency],
        ["Effective Rate", result.effectiveRate.toFixed(1) + "%", ""],
        ["Net Take-Home", result.netIncome.toFixed(2), j.currency],
        ["", "", ""],
        ["Filing Deadline", j.filingDeadline, ""],
        ...j.incentives.map((inc) => ["Available Incentive", inc, ""]),
        ...j.complianceNotes.map((n) => ["Compliance Note", n, ""])
      ]
    );
  }

  function handlePrint() {
    if (!result || !j) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`<!DOCTYPE html><html><head><title>Tax Report - ${j.name}</title>
<style>body{font-family:Arial,sans-serif;max-width:750px;margin:40px auto;color:#222}
h1{color:#cc0029}h2{color:#333;margin-top:30px}table{width:100%;border-collapse:collapse;margin:15px 0}
th,td{padding:8px 12px;text-align:left;border-bottom:1px solid #ddd}th{background:#f5f5f5}
.total{font-weight:700;border-top:2px solid #333}ul{margin:10px 0}li{margin:5px 0}
.badge{display:inline-block;background:#e8f5e9;color:#2e7d32;padding:2px 8px;border-radius:4px;font-size:12px;margin:2px}
</style></head><body>
<h1>🍒 CherryStim — Tax Compliance Report</h1>
<p><strong>Jurisdiction:</strong> ${j.name} | <strong>Currency:</strong> ${j.currency} | <strong>Filing Deadline:</strong> ${j.filingDeadline}</p>
<h2>Tax Calculation</h2>
<table><tr><th>Item</th><th>Amount</th></tr>
<tr><td>Gross Income</td><td>${j.currencySymbol}${result.grossIncome.toLocaleString()}</td></tr>
<tr><td>Deductions</td><td>-${j.currencySymbol}${result.totalDeductions.toLocaleString()}</td></tr>
<tr><td>Taxable Income</td><td>${j.currencySymbol}${result.taxableIncome.toLocaleString()}</td></tr>
<tr><td>Income Tax</td><td>${j.currencySymbol}${Math.round(result.incomeTax).toLocaleString()}</td></tr>
<tr><td>${j.socialLabel}</td><td>${j.currencySymbol}${Math.round(result.socialTax).toLocaleString()}</td></tr>
<tr class="total"><td>Total Tax Liability</td><td>${j.currencySymbol}${Math.round(result.totalTax).toLocaleString()} (${result.effectiveRate.toFixed(1)}%)</td></tr>
<tr class="total"><td>Net Take-Home</td><td style="color:#2e7d32;font-size:1.1em">${j.currencySymbol}${Math.round(result.netIncome).toLocaleString()}</td></tr></table>
<h2>Available Deductions</h2><table><tr><th>Deduction</th><th>Amount</th></tr>
${j.deductions.map((d) => `<tr><td>${d.name}</td><td>${j.currencySymbol}${d.amount.toLocaleString()}</td></tr>`).join("")}</table>
<h2>Tax Incentives & Credits</h2><ul>${j.incentives.map((i) => `<li><span class="badge">✓</span> ${i}</li>`).join("")}</ul>
<h2>Compliance Requirements</h2><ul>${j.complianceNotes.map((n) => `<li>⚠️ ${n}</li>`).join("")}</ul>
<h2>Tax Brackets</h2><table><tr><th>From</th><th>To</th><th>Rate</th></tr>
${j.brackets.map((b) => `<tr><td>${j.currencySymbol}${b.min.toLocaleString()}</td><td>${b.max === Infinity ? "∞" : j.currencySymbol + b.max.toLocaleString()}</td><td>${(b.rate * 100).toFixed(0)}%</td></tr>`).join("")}</table>
<p style="margin-top:40px;font-size:0.75em;color:#999">Generated by CherryStim Tax Module • ${new Date().toLocaleDateString()} • For informational purposes — consult a licensed tax professional.</p>
</body></html>`);
    win.document.close();
    win.print();
  }

  return (
    <Card className={`glass overflow-hidden ${className || ""}`}>
      <div className="flex items-center justify-between border-b border-white/10 px-6 py-4">
        <div className="flex items-center gap-2">
          <Globe size={18} className="text-emerald-400" />
          <h3 className="text-lg font-semibold">Global Tax Compliance Module</h3>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={handleExportCSV}><Download size={13} className="mr-1" /> CSV</Button>
          <Button variant="outline" size="sm" onClick={handlePrint}><Printer size={13} className="mr-1" /> Print</Button>
        </div>
      </div>

      <div className="p-6">
        <div className="mb-5 grid grid-cols-1 gap-4 md:grid-cols-2">
          <div>
            <label className="mb-1 block text-xs text-white/50">Annual Gross Income</label>
            <input type="number" value={income} onChange={(e) => setIncome(Number(e.target.value))} className="w-full rounded-xl border border-white/10 bg-black/40 px-4 py-2.5 text-sm focus:border-emerald-500 focus:outline-none" />
          </div>
          <div>
            <label className="mb-1 block text-xs text-white/50">Tax Jurisdiction</label>
            <select value={jurisdictionCode} onChange={(e) => setJurisdictionCode(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/40 px-4 py-2.5 text-sm focus:border-emerald-500 focus:outline-none">
              {JURISDICTIONS.map((jur) => <option key={jur.code} value={jur.code}>{jur.name}</option>)}
            </select>
          </div>
        </div>

        {result && j && (
          <>
            <div className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4">
              <div className="rounded-xl bg-white/[0.03] p-3 text-center">
                <p className="text-[10px] uppercase text-white/40">Income Tax</p>
                <p className="text-lg font-bold">{j.currencySymbol}{Math.round(result.incomeTax).toLocaleString()}</p>
              </div>
              <div className="rounded-xl bg-white/[0.03] p-3 text-center">
                <p className="text-[10px] uppercase text-white/40">{j.socialLabel.split("(")[0]}</p>
                <p className="text-lg font-bold">{j.currencySymbol}{Math.round(result.socialTax).toLocaleString()}</p>
              </div>
              <div className="rounded-xl bg-cherry-500/10 p-3 text-center">
                <p className="text-[10px] uppercase text-white/40">Total Tax</p>
                <p className="text-lg font-bold text-cherry-500">{j.currencySymbol}{Math.round(result.totalTax).toLocaleString()}</p>
                <p className="text-[9px] text-white/40">{result.effectiveRate.toFixed(1)}% effective</p>
              </div>
              <div className="rounded-xl bg-emerald-500/10 p-3 text-center">
                <p className="text-[10px] uppercase text-white/40">Net Take-Home</p>
                <p className="text-lg font-bold text-emerald-400">{j.currencySymbol}{Math.round(result.netIncome).toLocaleString()}</p>
              </div>
            </div>

            <div className="mb-4">
              <h4 className="mb-2 flex items-center gap-1 text-sm font-semibold"><CheckCircle2 size={14} className="text-emerald-400" /> Tax Incentives & Credits</h4>
              <div className="flex flex-wrap gap-1.5">
                {j.incentives.map((inc) => <span key={inc} className="rounded-lg bg-emerald-500/10 px-2 py-1 text-[10px] text-emerald-400">{inc}</span>)}
              </div>
            </div>

            <div className="mb-4">
              <h4 className="mb-2 flex items-center gap-1 text-sm font-semibold"><Shield size={14} className="text-gold-400" /> Compliance Requirements</h4>
              <div className="space-y-1">
                {j.complianceNotes.map((note) => <p key={note} className="text-xs text-white/50">⚠️ {note}</p>)}
              </div>
            </div>

            <div>
              <h4 className="mb-2 flex items-center gap-1 text-sm font-semibold"><Info size={14} className="text-sky-400" /> Filing Deadline: {j.filingDeadline}</h4>
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead><tr className="text-white/40"><th className="pb-1 text-left">From</th><th className="pb-1 text-left">To</th><th className="pb-1 text-left">Rate</th></tr></thead>
                  <tbody>
                    {j.brackets.map((b, i) => (
                      <tr key={i} className="border-t border-white/5">
                        <td className="py-1">{j.currencySymbol}{b.min.toLocaleString()}</td>
                        <td>{b.max === Infinity ? "∞" : j.currencySymbol + b.max.toLocaleString()}</td>
                        <td>{(b.rate * 100).toFixed(0)}%</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </>
        )}
      </div>
    </Card>
  );
}
